### PR TITLE
Add an optional cache buster for the debian images

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by reaperhulk** [comment]
Is this the current best practice docker suggests? I know they used to just suggest putting a comment with the date on the line you wanted to cache bust, but maybe that's not the way any more?

**Comment by alex** [comment]
@reaperhulk wat. is a comment really enough to blow it away?

**Comment by reaperhulk** [comment]
Yep!

**Comment by alex** [comment]
FWIW, I don't see anything about adding comments for cache busting in https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/

**Pull request merged**
