### PR TITLE
pin wheel on windows to 0.29, which is the last version to support py…

### PR DESCRIPTION
**Pull request by alex**
…thon 2.6

### CODE REVIEW

**Comment by alex** [comment]
Alternatively, we can drop windows py26 wheels.

**Comment by reaperhulk** [comment]
Lets drop the wheels and see what happens in the next release. Although I guess we should look up download counts first. I’ll wager they are extremely low.

**Comment by alex** [comment]
Can you look them up?

**Comment by reaperhulk** [comment]
Tomorrow. Past midnight here now

**Comment by reaperhulk** [comment]
Wheel download counts in the last 30 days: out of over 5 million downloads the Python 2.6 windows and macOS wheels accounted for just over 1000 total. We should go ahead and drop them (hopefully that will encourage 2.6 users to continue to migrate off that ancient Python too)

**Pull request closed without merging**
