### PR TITLE
Fixed #7 -- unit files for running caddy and the jenkins server

### LINKED ISSUE #7: Write systemd unit files
We need systemd unit files to launch caddy & jenkins.

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by alex** [comment]
Perhaps goes without saying, but this is 100% untested.

**Comment by alex** [comment]
Does the `caddy` service need to depend on `jenkins` one, or is it fine to start in either order.

**Comment by reaperhulk** [comment]
caddy needs the jenkins container to exist (for `--link`) but other than that it doesn't matter. Since we're using `--rm` that probably means caddy should depend on jenkins.

**Comment by alex** [comment]
Without `--rm` my experience is one leaks containers left and right. Will make it depend.

**Pull request merged**
