### PR TITLE
remove py27 from containers (except stretch)

### PR DESCRIPTION
**Pull request by reaperhulk**

### CODE REVIEW

**Comment by alex** [comment]
Do we merge this now, or wait until 3.4 is released? We'll want these as long as there's any chance we'll have to do a 3.3.1 in a week for another OpenSSL release.

**Comment by reaperhulk** [comment]
I think we probably wait until 3.4

**Comment by alex** [comment]
kk, converting to a draft.

**Comment by reaperhulk** [comment]
When we release 3.4 and merge this we should also do a PR to remove building MSVC2010 OpenSSL

**Comment by alex** [comment]
Note: we're now using py2 in debian stretch container to test pyOpenSSL.

**Review by alex — APPROVED** [review]

**Pull request merged**
