### PR TITLE
Fixed caddy dockerfile for new caddy website

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by alex** [comment]
see here it's failing: https://travis-ci.org/pyca/infra/builds/224184224#L479

**Comment by reaperhulk** [comment]
So, no more plugins?

**Comment by alex** [comment]
@reaperhulk they do have plugins, but prometheus isn't listed on the website. I figured the right thing to do was get it building again -- since we aren't using prometheus ATM. And then figure out what the right way to bring it back was.

**Comment by reaperhulk** [comment]
Yeah I was just looking and see the prometheus plugin is MIA. Okay then!

**Pull request merged**
