### PR TITLE
use failfast so we can see all the broken

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by alex** [comment]
Potential fix here: https://github.com/pypa/manylinux/pull/1278

**Comment by alex** [comment]
Nope, that fix was not correct.

**Comment by mayeut** [comment]
@alex,
could not find anything related to a server outage for mirrors.fedoraproject.org which should be the origin for the error seen.
I see this happened twice 2 days ago, are you able to reproduce somewhere else (I can't). Might have been some transient network errors ?
Can you restart the failing workflows to see if this indeed disappeared ?
potential mitigation is probably to disable epel on your end if you don't need it. Something like that should work:
```
if yum-config-manager --version &> /dev/null; then yum-config-manager --disable epel; fi
```

**Comment by alex** [comment]
@mayeut Well, this is emberassing, looks like you're right that it was a flake that we over-interpreted.

**Review by reaperhulk — APPROVED** [review]

**Comment by mayeut** [comment]
no worries.
FYI, at first I thought there was a typo in the PR you opened as we're seeing `yum install`/`yum update` occasional issues on `manylinux2010` which already uses the vault... I was about to open pypa/manylinux#1281 when I saw your PR. I see that cryptography is planning dropping this as well https://github.com/pyca/cryptography/pull/6694

**Comment by alex** [comment]
@mayeut yes https://github.com/pyca/cryptography/pull/6831 documents our plan (the next release will be the last one to support manylinux2010 and the release after that will drop it)

**Pull request merged**
