### PR TITLE
Install jenkins plugins automatically

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by reaperhulk** [comment]
Where do these plugins live in the container? Normally installed plugins live in `$JENKINS_HOME/plugins`, but in our configuration that's a mounted docker volume that is writeable (unlike the container itself, which we run as --readonly).

**Comment by alex** [comment]
I think `/usr/share`, but the FS is writable at build time: https://github.com/jenkinsci/docker/blob/master/install-plugins.sh

**Comment by reaperhulk** [comment]
I wonder if /usr/share plugins are the default set and then upgrades write into $JENKINS_HOME/plugins then? I'm mostly concerned about the fact that in the current scenario if a plugin update is bad we can actually revert in the UI, but a new container build that bakes in the latest broken version would prevent that.

**Comment by reaperhulk** [comment]
This will never happen since we're killing jenkins

**Pull request closed without merging**
